### ISSUE TITLE
[Todo] 5/21 

### ISSUE THREAD

**Issue by BeautterLife** [kookmin-sw/capstone-2021-23#71]
- [x] email 전송 기능 마무리
- [x] master branch merge 후 version2 생성
- [x] cctv 관련 view 매끄럽게 수정
- [x] cctv_db branch 커밋 마무리
